name: Arsip HK Otomatis

on:
  push:
    paths:
      - "data/data-hk.js"

jobs:
  buat-arsip:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Jalankan pembuat arsip
      run: node buat-arsip.js

    - name: Commit arsip
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add data/arsip-hk.js
        git commit -m "Update arsip otomatis" || exit 0
        git push
